LOCAL_DIR := $(GET_LOCAL_DIR)

INCLUDES += -I$(LOCAL_DIR)/include -I$(LK_TOP_DIR)/platform/msm_shared/include
INCLUDES += -I$(LOCAL_DIR)/include
INCLUDES += -I$(LK_TOP_DIR)/target/msm8916_common/include

ENABLE_LGE_WITH_BOOT_MODE := 1
ENABLE_LGE_WITH_SELECT_MODE := 1
ENABLE_LGE_WITH_FTM := 1
ENABLE_LGE_WITH_DEVICE_TREE := 1
ENABLE_LGE_WITH_SBL_LOG := 1
#ENABLE_LGE_WITH_FLEXIBLE_GPT := 1

ifeq ($(ENABLE_LGE_WITH_BOOT_MODE),1)
DEFINES += LGE_WITH_BOOT_MODE
OBJS += $(LOCAL_DIR)/lge_bootcmd.o
OBJS += $(LOCAL_DIR)/lge_smem.o
OBJS += $(LOCAL_DIR)/lge_bootmode.o
endif

DEFINES += LGE_WITH_SMEM_VENDOR
DEFINES += LGE_WITH_SMEM_PON_STATUS

ifeq ($(ENABLE_LGE_WITH_SELECT_MODE),1)
DEFINES += LGE_WITH_SELECT_MODE
OBJS += $(LOCAL_DIR)/lge_select_mode.o
endif

ifeq ($(ENABLE_LGE_WITH_FTM), 1)
DEFINES += LGE_WITH_FTM
OBJS += $(LOCAL_DIR)/lge_ftm.o
endif

ifeq ($(ENABLE_LGE_WITH_DEVICE_TREE), 1)
DEFINES += LGE_WITH_DEVICE_TREE
OBJS += $(LOCAL_DIR)/lge_dev_tree.o
endif

ifeq ($(ENABLE_LGE_WITH_SBL_LOG), 1)
DEFINES += LGE_WITH_SBL_LOG
OBJS += $(LOCAL_DIR)/lge_sbl_log.o
endif

DEFINES += LGE_MINIOS3_BOOT
DEFINES += LGE_MINIOS3_FRESET
DEFINES += LGE_WITH_BOOTLOADER_LOG_SAVE

ifeq ($(ENABLE_LGE_WITH_FLEXIBLE_GPT),1)
DEFINES += LGE_WITH_FLEXIBLE_GPT
DEFINES += LGE_WITH_RESIZE_DATA
OBJS += $(LOCAL_DIR)/lge_partition.o
endif

ifneq ($(TARGET_BUILD_VARIANT),user)
DEFINES += LGE_WITH_CRASH_HANDLER
endif

ifeq ($(TARGET_BUILD_VARIANT),user)
DEFINES += LGE_WITH_DISABLE_FASTBOOT
endif

ifneq ($(VERIFIED_BOOT),1)
DEFINES += LGE_SECUREBOOT

ifeq ($(SECUREBOOT_LK_CC_DISABLED),1)
    DEFINES += LGE_SECUREBOOT_DISABLE_IN_CC_MODE
endif

ifneq ($(SECUREBOOT_LK_NOT_USE_HW_CRYPTO),1)
    DEFINES += LGE_QCT_HW_CRYPTO
endif

ifeq ($(ENABLE_BL_UNLOCK_SUPPORT),1)
    DEFINES += LGE_BOOTLOADER_UNLOCK
endif

ifeq ($(ENABLE_KILLSWITCH_UNLOCK_SUPPORT),1)
    DEFINES += LGE_KILLSWITCH_UNLOCK
endif

ifeq ($(TARGET_BUIJLD_VARIANT),user)
    DEFINES += BOOT_INTEGRITY_USER_BUILD
endif

DEFINES += LGE_CHECK_GPT_INTEGRITY

OBJS += \
    $(LOCAL_DIR)/lge_verified_boot.o \
    $(LOCAL_DIR)/lge_bl_unlock.o \
    $(LOCAL_DIR)/keys/$(SECUREBOOT_KEYALIAS)/verified_boot.o \
    $(LOCAL_DIR)/keys/bl_unlock.o \
    $(LOCAL_DIR)/keys/$(KSUT_KEYALIAS)/kill_switch.o

OBJS += $(LOCAL_DIR)/lge_splash_screen.o
OBJS += $(LOCAL_DIR)/lge_kswitch.o

endif
